apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: ediscan-alerts
        rules:
          - alert: EdiScanDown
            expr: up{job="ediscan"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "EdiScan is down"
              description: "EdiScan has been down for more than 1 minute."

          - alert: HighCPUUsage
            expr: avg(rate(container_cpu_usage_seconds_total{pod=~"ediscan.*"}[5m])) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on EdiScan"
              description: "CPU usage is above 80% for more than 5 minutes."

          - alert: HighMemoryUsage
            expr: avg(container_memory_usage_bytes{pod=~"ediscan.*"}) / avg(container_spec_memory_limit_bytes{pod=~"ediscan.*"}) * 100 > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on EdiScan"
              description: "Memory usage is above 85% for more than 5 minutes."

          - alert: HighResponseTime
            expr: histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{job="ediscan"}[5m])) by (le)) > 5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High response time on EdiScan"
              description: "95th percentile response time is above 5 seconds."

          - alert: PodRestartingTooMuch
            expr: increase(kube_pod_container_status_restarts_total{pod=~"ediscan.*"}[1h]) > 5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "EdiScan pod is restarting frequently"
              description: "Pod has restarted more than 5 times in the last hour."

